"""Export scan summaries and detailed cleanup reports."""

from __future__ import annotations

import csv
from pathlib import Path

from downloads_cleanup_assistant import __app_name__, __author__

from .models import ScanResult
from .utils import human_size


class ReportExporter:
    """Create portfolio-friendly reports from scan results."""

    def export_text_summary(self, result: ScanResult, path: Path) -> None:
        """Export a readable scan summary."""

        lines = [
            f"Application: {__app_name__}",
            f"Generated By: {__author__}",
            f"Date: {result.scanned_at:%Y-%m-%d %H:%M:%S}",
            "",
            "Summary:",
            f"Folder scanned: {result.folder}",
            f"Files scanned: {len(result.files)}",
            f"Total storage used: {human_size(result.total_size)}",
            f"Duplicates found: {result.duplicate_files_count}",
            f"Large files found: {len(result.large_files)}",
            f"Old files found: {len(result.old_files)}",
            f"Estimated recoverable space: {human_size(result.recoverable_size)}",
            "",
            "Recommendations:",
        ]
        if result.recommendations:
            for item in result.recommendations:
                lines.append(f"- {item.title}: {human_size(item.potential_savings)} - {item.description}")
        else:
            lines.append("- No cleanup recommendations were found.")
        path.write_text("\n".join(lines), encoding="utf-8")

    def export_csv_inventory(self, result: ScanResult, path: Path) -> None:
        """Export the full file inventory for spreadsheets."""

        with path.open("w", newline="", encoding="utf-8") as file:
            writer = csv.writer(file)
            writer.writerow(
                [
                    "Name",
                    "Path",
                    "Category",
                    "Size Bytes",
                    "Modified",
                    "Age Days",
                    "Duplicate",
                    "Large",
                    "Old",
                    "Duplicate Group",
                ]
            )
            for record in result.files:
                writer.writerow(
                    [
                        record.name,
                        str(record.path),
                        record.category,
                        record.size,
                        record.modified_at.isoformat(sep=" ", timespec="seconds"),
                        record.age_days,
                        "Yes" if record.is_duplicate else "No",
                        "Yes" if record.is_large else "No",
                        "Yes" if record.is_old else "No",
                        record.duplicate_group or "",
                    ]
                )
